# Maintainer: Eduard Kiss <e.kiss@office.ngs.ru>
pkgname=zbackup
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc="multithreading zfs backuper written on golang"
arch=('i686' 'x86_64')
license=('GPL')
depends=()
makedepends=(
	'go'
	'git'
	'dep'
)
backup=('etc/zbackup/zbackup.conf')
branch=${BRANCH:-master}
source=("${pkgname}::git+https://github.com/HolyGhost07/zbackup#branch=${branch}")
md5sums=(
	'SKIP'
)

pkgver() {
	if [[ "$PKGVER" ]]; then
		echo "$PKGVER"
		return
	fi

	cd "$srcdir/$pkgname"
	local date=$(git log -1 --format="%cd" --date=short | sed s/-//g)
	local count=$(git rev-list --count HEAD)
	local commit=$(git rev-parse --short HEAD)
    
	echo "$date.${count}_$commit"
}

build() {
	cd "$srcdir/$pkgname"

	rm -rf "$srcdir/.go/src"
    mkdir -p "$srcdir/.go/src/github.com/HolyGhost07"

    export GOPATH="$srcdir/.go"

    mv "$srcdir/$pkgname" "$srcdir/.go/src/github.com/HolyGhost07"
    cd "$srcdir/.go/src/github.com/HolyGhost07/$pkgname"

    make
}

package() {
	cd "$srcdir/.go/src/github.com/HolyGhost07/$pkgname"

	install -Dm 0755 ".out/$pkgname" "$pkgdir/usr/bin/$pkgname"
    install -Dm 644 zbackup.conf "$pkgdir/etc/zbackup.conf"
}
